### ISSUE TITLE
Максимально использовать библиотечные функции вместо самописных

### ISSUE THREAD

**Issue by kuritsynk** [Arinarina/Lab_1#1]
https://github.com/Arinarina/Lab_1/blob/0c4b1543fc454b8af492cf12c9b06af3e5030e4f/Labarator_1/func.h#L18 - название функции не говорящее.

Следует посмотреть на стандартные решения для работы со строками: ``std::string`` и, вообще,``std``.

Для сортировки массива не нужно писать свою функцию. Следует воспользоваться стандартной функцией сортировки ``std::sort``, в которую передать функцию сравнения двух элементов (экземпляров класса).

**Comment by Arinarina** [comment]
Максимально использовать библиотечные функции вместо самописных
