### ISSUE TITLE
Сделать код main более читабельным

### ISSUE THREAD

**Issue by kuritsynk** [Arinarina/Lab_1#3]
https://github.com/Arinarina/Lab_1/blob/0c4b1543fc454b8af492cf12c9b06af3e5030e4f/Labarator_1/main.cpp#L14

Во многих местах используется 10 - заменить на константу.

Разбить функцию на отдельные, дать им "говорящие" названия.

**Comment by Arinarina** [comment]
Константа была добавлена в прошлом коммите, как и говорящие названия
