### ISSUE TITLE
Убрать из общего модуля func ссылки на worker.

### ISSUE THREAD

**Issue by kuritsynk** [Arinarina/Lab_1#4]
https://github.com/Arinarina/Lab_1/blob/b3dd28421ae53c2275c48b97ee0ea1406fea6807/Labarator_1/func.cpp#L51

Функцию сортировки массива перенести в worker. 

Избавиться от функций func, которые могут быть легко заменены на стандартный (например, strcpy, strlen и т.п.).

**Comment by kuritsynk** [comment]
В коммите b3dd28421ae53c2275c48b97ee0ea1406fea6807 в рамках #1 как раз заменялось использование упомянутых функций на стандартные. Из func теперь надо убрать неиспользуемые функции.

**Comment by Arinarina** [comment]
Убрать из общего модуля func ссылки на worker.
